name: error_stack
description: "ErrorStack helps you swiftly deal with errors in your Flutter applications! Custom error handling UI and logging to keep you productive."
version: 1.5.0
homepage: https://nylo.dev
repository: https://github.com/nylo-core/error-stack/tree/1.x
issue_tracker: https://github.com/nylo-core/error-stack/issues
documentation: https://github.com/nylo-core/error-stack
funding:
  - https://github.com/sponsors/agordn52
topics:
  - error-handling
  - error-ui
  - logging
  - custom-error

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter_secure_storage: ^9.2.2
  url_launcher: ^6.3.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

screenshots:
  - description: The Error Stack logo.
    path: screenshots/logo.png

flutter:

